runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1

default_expiration: "1d"

handlers:
- url: /source_info/.*|^/source_info$
  script: SourceInfo.app

- url: /verification/.*|^/verification$
  script: Verification.app

- url: /_ah/admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

- url: .*
  script: main.app

builtins:
- remote_api: on
- appstats: on

libraries:
- name: webapp2
  version: latest

- name: MySQLdb
  version: latest

- name: django
  version: latest

- name: pycrypto
  version: latest

- name: lxml
  version: latest

- name: endpoints
  version: 1.0

- name: jinja2
  version: latest

- name: ssl
  version: latest

- name: numpy
  version: latest


env_variables:
  GAE_USE_SOCKETS_HTTPLIB : ''